name: Demo Deploy
concurrency: 1
on:
  push:
    branches:
      - develop
    paths:
      - "my_project/**"
jobs:
  deploy:
    name: "Deploy bundle"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: databricks/setup-cli@main

      - run: databricks bundle deploy
        working-directory: ./my_project
        env:
          DATABRICKS_TOKEN: ${{ secrets.E2_SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
  pipeline_update:
    name: "Run pipeline update"
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle run my_project_pipeline --refresh-all
        working-directory: ./my_project
        env:
          DATABRICKS_TOKEN: ${{ secrets.E2_SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev
